
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("AG","Agrigento","Sicilia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("AL","Alessandria","Piemonte");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("AN","Ancona","Marche");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("AO","Valle d'Aosta","Valle d'Aosta");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("AP","Ascoli Piceno","Marche");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("AQ","L'Aquila","Abruzzo");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("AR","Arezzo","Toscana");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("AT","Asti","Piemonte");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("AV","Avellino","Campania");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("BA","Bari","Puglia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("BG","Bergamo","Lombardia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("BI","Biella","Piemonte");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("BL","Belluno","Veneto");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("BN","Benevento","Campania");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("BO","Bologna","Emilia-Romagna");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("BR","Brindisi","Puglia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("BS","Brescia","Lombardia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("BT","Barletta-Andria-Trani","Puglia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("BZ","Bolzano","Trentino-Alto Adige");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("CA","Cagliari","Sardegna");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("CB","Campobasso","Molise");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("CE","Caserta","Campania");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("CH","Chieti","Abruzzo");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("CI","Carbonia-Iglesias","Sardegna");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("CL","Caltanissetta","Sicilia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("CN","Cuneo","Piemonte");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("CO","Como","Lombardia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("CR","Cremona","Lombardia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("CS","Cosenza","Calabria");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("CT","Catania","Sicilia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("CZ","Catanzaro","Calabria");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("EN","Enna","Sicilia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("FC","Forli-Cesena","Emilia-Romagna");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("FE","Ferrara","Emilia-Romagna");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("FG","Foggia","Puglia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("FI","Firenze","Toscana");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("FM","Fermo","Marche");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("FR","Frosinone","Lazio");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("GE","Genova","Liguria");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("GO","Gorizia","Friuli-Venezia Giulia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("GR","Grosseto","Toscana");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("IM","Imperia","Liguria");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("IS","Isernia","Molise");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("KR","Crotone","Calabria");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("LC","Lecco","Lombardia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("LE","Lecce","Puglia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("LI","Livorno","Toscana");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("LO","Lodi","Lombardia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("LT","Latina","Lazio");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("LU","Lucca","Toscana");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("MB","Monza e della Brianza","Lombardia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("MC","Macerata","Marche");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("ME","Messina","Sicilia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("MI","Milano","Lombardia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("MN","Mantova","Lombardia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("MO","Modena","Emilia-Romagna");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("MS","Massa-Carrara","Toscana");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("MT","Matera","Basilicata");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("NA","Napoli","Campania");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("NO","Novara","Piemonte");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("NU","Nuoro","Sardegna");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("OG","Ogliastra","Sardegna");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("OR","Oristano","Sardegna");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("OT","Olbia-Tempio","Sardegna");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("PA","Palermo","Sicilia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("PC","Piacenza","Emilia-Romagna");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("PD","Padova","Veneto");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("PE","Pescara","Abruzzo");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("PG","Perugia","Umbria");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("PI","Pisa","Toscana");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("PN","Pordenone","Friuli-Venezia Giulia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("PO","Prato","Toscana");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("PR","Parma","Emilia-Romagna");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("PT","Pistoia","Toscana");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("PU","Pesaro e Urbino","Marche");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("PV","Pavia","Lombardia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("PZ","Potenza","Basilicata");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("RA","Ravenna","Emilia-Romagna");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("RC","Reggio di Calabria","Calabria");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("RE","Reggio Emilia","Emilia-Romagna");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("RG","Ragusa","Sicilia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("RI","Rieti","Lazio");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("RM","Roma","Lazio");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("RN","Rimini","Emilia-Romagna");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("RO","Rovigo","Veneto");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("SA","Salerno","Campania");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("SI","Siena","Toscana");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("SO","Sondrio","Lombardia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("SP","La Spezia","Liguria");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("SR","Siracusa","Sicilia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("SS","Sassari","Sardegna");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("SV","Savona","Liguria");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("TA","Taranto","Puglia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("TE","Teramo","Abruzzo");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("TN","Trento","Trentino-Alto Adige");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("TO","Torino","Piemonte");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("TP","Trapani","Sicilia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("TR","Terni","Umbria");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("TS","Trieste","Friuli-Venezia Giulia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("TV","Treviso","Veneto");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("UD","Udine","Friuli-Venezia Giulia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("VA","Varese","Lombardia");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("VB","Verbano-Cusio-Ossola","Piemonte");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("VC","Vercelli","Piemonte");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("VE","Venezia","Veneto");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("VI","Vicenza","Veneto");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("VR","Verona","Veneto");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("VS","Medio Campidano","Sardegna");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("VT","Viterbo","Lazio");
INSERT INTO `province` (`cod`,`nome`,`regione`) VALUES ("VV","Vibo Valentia","Calabria");
